apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo-cluster-three-tier-1
  region: us-east-2
  version: "1.32"

# OIDC zaroor enable karein, ye add-ons ke liye zaroori hai
iam:
  withOIDC: true 

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.small
    minSize: 3
    maxSize: 5
    desiredCapacity: 3
    volumeSize: 20



# E33929F2E13941C0B961E6AB95D18E5B
# this is aes iam list-open
# 23A9A17AEAB5EA4BD0B37342F11D692F"
    